modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "acrylic"
version = "${version}"
displayName = "AcryliCraft"
authors = "DevBobcorn"
description = '''
Apply Fluent Design materials to Minecraft window.
'''
#logoFile = ""

[[dependencies.acrylic]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acrylic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acrylic]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.89,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.acrylic]]
modId="yet_another_config_lib_v3"
mandatory=true
versionRange="[3.1.0,)"
ordering="AFTER"
side="CLIENT"