modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "acrylic"
version = "${version}"
displayName = "AcryliCraft"
authors = "DevBobcorn"
description = '''
Apply Fluent Design materials to Minecraft window.
'''
logoFile = "assets/acrylic/acrylicraft.png"

[[dependencies.acrylic]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acrylic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acrylic]]
modId="yet_another_config_lib_v3"
mandatory=true
versionRange="[3.2.2,)"
ordering="AFTER"
side="CLIENT"